# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddb3aa8ae9691e43f0cdd9428fe3c13c8d4f3cb57a74720a5e3d8a63cfa00e1e64344aa6d69860e8ab6e9e1ff0c6e8240ca4839b40df4dad4f6bf82d5c17d1d

test:
  secret_key_base: bde3ecdab72372c14b134caca9e4c5bcb2e81aecaf50f0271ddc3391dc4a356d8760b73081191c1c1cdf1f24a2c0ccaee01f9463ae7d11c7446981a7ee124e00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
